apiVersion: v2
name: languagetool
description: polish your writing and grammar in various languages
type: application
version: 0.1.9
appVersion: "6.3"

home: https://languagetool.org/
icon: https://languagetool.org/images/logo_white.svg
sources:
  - https://github.com/languagetool-org/languagetool
  - https://github.com/Erikvl87/docker-languagetool
keywords:
  - Utilities

annotations:
  displayName: languagetool
  licenses: LGPL-2.1 license
  category: Utilities
  gallery: |
    