apiVersion: v2
name: drawio
description: Online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams.
type: application
version: 0.1.49
appVersion: "24.4.13"
home: https://www.drawio.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/drawio/drawio_icon_2.svg
sources:
  - https://github.com/jgraph/drawio
  - https://github.com/jgraph/docker-drawio
maintainers:
  - name: JGraph Ltd and draw.io AG
    url: https://github.com/jgraph/drawio
keywords:
  - Diagrams
annotations:
  displayName: draw.io
  category: Design
  licenses: Apache-2.0
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/drawio/drawio_gallery_1.webp
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/drawio/drawio_gallery_2.webp
