apiVersion: v2
name: observability-stack
description: An all-in-one observability stack for Kubernetes, integrating Grafana, Prometheus, Loki, Tempo, Promtail, and Pyroscope.
version: 0.0.85
appVersion: v0.73.2
dependencies:
  - name: kube-prometheus-stack
    version: 58.4.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
  - name: loki
    version: 6.5.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.7.3
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.15.5
    repository: https://grafana.github.io/helm-charts
  - name: pyroscope
    version: 1.5.1
    repository: https://grafana.github.io/helm-charts
home: https://grafana.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_icon_2.svg
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/loki
  - https://github.com/grafana/tempo
  - https://github.com/grafana/pyroscope
  - https://github.com/prometheus/prometheus
keywords:
  - Observability
  - Metrics
  - Logging
  - Alerting
annotations:
  displayName: Observability Stack
  category: Developer Tools
  licenses: Apache-2.0
  gallery: |-
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_gallery_1.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_gallery_2.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_gallery_3.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_gallery_4.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_gallery_5.png
