apiVersion: v2
name: nextcloud
description: A safe home for all your data â€“ community-driven, free & open source.
type: application
version: 0.0.31
appVersion: "27.1.2"
dependencies:
  - name: nextcloud
    version: 4.6.2
    repository: https://nextcloud.github.io/helm/
home: https://nextcloud.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/nextcloud/nextcloud_icon_2.svg
annotations:
  displayName: Nextcloud
  category: Utilities
  licenses: AGPL-3.0
  gallery: |
    https://raw.githubusercontent.com/nextcloud/screenshots/master/nextcloud-hub-files-25-preview.png
