apiVersion: v2
name: uptrace
description: Open Source Observability with Traces, Metrics, and Logs
type: application
version: 0.0.11
appVersion: "1.7.7"
home: https://uptrace.dev/
icon: https://raw.githubusercontent.com/monostream/emporium-catalog/main/assets/uptrace/uptrace_icon_2.svg
sources:
  - https://github.com/uptrace/helm-charts/
keywords:
  - Observability
  - Tracing
  - Logs
  - Metrics
  - Alerting
dependencies:
  - name: uptrace
    version: 1.7.7
    repository: https://charts.uptrace.dev
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
annotations:
  displayName: Uptrace
  licenses: AGPL-3.0
  category: Monitoring
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/uptrace/uptrace_gallery_1.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/uptrace/uptrace_gallery_2.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/uptrace/uptrace_gallery_3.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/uptrace/uptrace_gallery_4.png
  oidcRedirectPaths: /internal/v1/sso/emporium/callback
