apiVersion: v2
name: n8n
description: A powerful workflow automation tool.
version: 0.1.13
appVersion: 1.22.3
dependencies:
  - name: n8n
    version: 0.22.0
    repository: oci://8gears.container-registry.com/library
home: https://n8n.io/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/n8n/n8n_icon_2.svg
sources:
  - https://github.com/n8n-io/n8n
  - https://github.com/8gears/n8n-helm-chart
maintainers:
  - name: n8n GmbH
    url: https://n8n.io
  - name: 8gears AG
    url: https://8gears.com/
keywords:
  - Automation
  - APIs
  - Integrations
type: application
annotations:
  displayName: n8n
  category: Utilities
  licenses: Sustainable Use License
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/n8n/n8n_gallery_1.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/n8n/n8n_gallery_2.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/n8n/n8n_gallery_3.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/n8n/n8n_gallery_4.jpg
