apiVersion: v2
name: rotki
description: An open-source portfolio tracking, analytics, accounting, and tax reporting tool that emphasizes user privacy and financial transparency.
type: application
version: 0.1.12
appVersion: "v1.35.0"
home: https://rotki.com/
icon: https://raw.githubusercontent.com/rotki/rotki/develop/frontend/app/public/assets/images/rotkehlchen_no_text.png # Rotki logo from GitHub
sources:
  - https://github.com/rotki/rotki
maintainers:
  - name: Rotki Solutions GmbH
    url: https://github.com/rotki/rotki
keywords:
  - Portfolio Tracking
  - Analytics
  - Accounting
  - Tax Reporting
  - Financial Management
annotations:
  displayName: Rotki
  category: Bitcoin
  licenses: AGPL-3.0
  gallery: |
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_blockchain_account.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_evm_address_book.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_exchange_api_keys_binance.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_external_service.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_tag_label.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/add_xpub_key.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/asset_overview.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/binance_markets_selection.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/contrib_dimens.png
    https://raw.githubusercontent.com/rotki/rotki/develop/docs/images/contrib_screen.png
