apiVersion: v2
name: gha-runner
description: GitHub Actions Runner orchestrates and scales self-hosted runners for GitHub Actions
version: 0.0.8
appVersion: 0.8.2
dependencies:
  - name: gha-runner-scale-set-controller
    version: 0.8.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
  - name: gha-runner-scale-set
    version: 0.8.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/gha-runner/gha-runner_icon_2.svg
sources:
  - https://github.com/actions/actions-runner-controller
keywords:
  - SelfHosted
  - CI/CD
annotations:
  displayName: GitHub Actions Runner
  category: Developer Tools
  licenses: Apache-2.0
