apiVersion: v2
name: forgejo
description: forgejo is a community managed lightweight code hosting solution written in Go. It is published under the MIT license.
type: application
version: 0.0.19
appVersion: "1.21.8-0"
dependencies:
  - name: forgejo
    version: 5.0.2
    repository: oci://codeberg.org/forgejo-contrib
home: https://forgejo.org/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/forgejo/forgejo_icon_3.svg
sources:
  - https://forgejo.com/forgejo/helm-chart
keywords:
  - Collaboration
  - Coding
  - Git
  - CI/CD
  - Issue Tracking
annotations:
  category: Developer Tools
  displayName: forgejo
  licenses: MIT
  oidcRedirectPaths: /user/oauth2/emporium/callback
