apiVersion: v2
name: forgejo-runner
description: Forgejo Actions Runner orchestrates and scales self-hosted runners for Gittea Actions
version: 0.0.24
appVersion: 3.3.0
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/forgejo/forgejo_icon_3.svg
sources:
  - https://codeberg.org/wrenix/helm-charts/src/branch/main/forgejo-runner
keywords:
  - SelfHosted
  - CI/CD
annotations:
  displayName: Forgejo Actions Runner
  category: Developer Tools
  licenses: Apache-2.0
