apiVersion: v2
name: vaultwarden
description: Lightweight, self-hosted vault for secure password managementâ€”privacy, control, and peace of mind at your fingertips.
type: application
version: 0.1.4
appVersion: "1.32.3"
home: https://github.com/dani-garcia/vaultwarden
icon: https://github.com/dani-garcia/vaultwarden/blob/main/resources/vaultwarden-icon-white.svg?raw=true
sources:
  - https://github.com/dani-garcia/vaultwarden
keywords:
  - Utilities
annotations:
  displayName: vaultwarden
  licenses: AGPL-3.0 license
  category: Utilities
  gallery: ""
