apiVersion: v2
name: onedev
description: Git Server with CI/CD, Kanban, and Packages. Seamless integration. Unparalleled experience.
type: application
version: 0.0.21
appVersion: "11.6.13"
dependencies:
  - name: onedev
    version: 11.6.13
    repository: https://dl.cloudsmith.io/public/onedev/onedev/helm/charts
home: https://onedev.io/
icon: https://docs.onedev.io/img/logo.svg
sources:
  - https://github.com/theonedev/onedev
keywords:
  - Collaboration
  - Coding
  - Git
  - CI/CD
  - Issue Tracking
annotations:
  category: Developer Tools
  displayName: onedev
  licenses: MIT
